smallrye/smallrye-health

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
* add addHealthCheck & removeHealthCheck method to SmallRyeHealthReporter
to be able to use it in a non-CDI environment.
* test nullability of the injected checks that are now null when the
instance is used in a non-CDI environment.
Issue: https://github.com/smallrye/smallrye-health/issues/3
> [#3] Use SmallRyeHealthReported in non-CDI environment

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
The MicroProfile Health spec says:
> When multiple procedures are installed all procedures MUST be executed and the overall status needs to be determined.
https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.adoc#policies-to-determine-the-overall-status
The SmallRye implementation short-circuits if a single procedure throws an unchecked exception.
This pull request is an idea of how to fix this by catching unchecked exceptions and fabricating a response. Probably want to make the generated response configurable to avoid leaking potentially sensitive information.
> handle unchecked exceptions thrown by health checks

- tck/pom.xml
Solves #5, makes TCK run with Java 11+
Works on Java 12-ea+23 too
> [#5] Make TCK run with Java 11+

- docs/pom.xml
- implementation/pom.xml
- pom.xml
- tck/pom.xml
> smallrye-health-42 Upgrade to MP Health 2.0

- implementation/src/main/java/io/smallrye/health/HealthStatus.java
- implementation/src/test/java/io/smallrye/health/HealthStatusTest.java
> feat(#50): Adds HealthStatus helper class

- implementation/src/main/java/io/smallrye/health/checks/InetAddressHealthCheck.java
- implementation/src/main/java/io/smallrye/health/checks/SocketHealthCheck.java
- implementation/src/main/java/io/smallrye/health/checks/UrlHealthCheck.java
- implementation/src/test/java/io/smallrye/health/checks/InetAddressHealthCheckTest.java
- implementation/src/test/java/io/smallrye/health/checks/SocketHealthCheckTest.java
- implementation/src/test/java/io/smallrye/health/checks/UrlHealthCheckTest.java
> feat(#53): Implements some useful health checks

- implementation/pom.xml
- pom.xml
- tck/pom.xml
Switch to SmallRye Parent 16
Add Guava to run tck (required for `testPayloadJsonVerifiesWithTheSpecificationSchema`).
> Switch to Jakarta EE artifacts

- extension-api/pom.xml
- extension-api/src/main/java/io/smallrye/health/HealthGroup.java
- extension-api/src/main/java/io/smallrye/health/HealthGroups.java
- extension-test/pom.xml
- extension-test/src/test/java/io/smallrye/health/SmallRyeBeanArchiveHandler.java
- extension-test/src/test/java/io/smallrye/health/SmallRyeHealthArchiveProcessor.java
- extension-test/src/test/java/io/smallrye/health/SmallRyeHealthExtension.java
- extension-test/src/test/java/io/smallrye/health/deployment/FailedCustom.java
- extension-test/src/test/java/io/smallrye/health/deployment/SuccessfulCustom.java
- extension-test/src/test/java/io/smallrye/health/tck/AllCustomFailedTest.java
- extension-test/src/test/java/io/smallrye/health/tck/DeploymentUtils.java
- extension-test/src/test/java/io/smallrye/health/tck/MultipleCustomFailedTest.java
- extension-test/src/test/java/io/smallrye/health/tck/SingleCustomSuccessfulTest.java
- extension-test/src/test/java/io/smallrye/health/tck/TCKBase.java
- extension-test/src/test/resources/META-INF/beans.xml
- extension-test/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
- extension-test/src/test/resources/arquillian.xml
- implementation/pom.xml
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- pom.xml
- tck/pom.xml
- tck/src/main/java/io/smallrye/health/SmallRyeHealthGroupServlet.java
- tck/src/test/resources/arquillian.xml
* Add the health groups feature
* Add a separate module for the additional spec API
* Add a separate module for the additional spec API testing
> Implement the health groups feature

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
Fixes #91
I used a static initliazer class to avoid a premature call to the ServiceLoader but maybe it's too much and I can just use an instance variable instead.
> Cache JsonProvider to avoid loading the ServiceLoader on each request

- api/src/main/java/io/smallrye/health/api/Wellness.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/FailedWellness.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessfulWellness.java
- testsuite/experimental/src/test/java/io/smallrye/health/tck/TCKBase.java
- testsuite/experimental/src/test/java/io/smallrye/health/tck/WellnessFailedTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/tck/WellnessSuccessfulTest.java
- testsuite/tck/src/main/java/io/smallrye/health/SmallRyeWellnessServlet.java
Fixes #41 by adding @Wellness HC and /well endpoint
> Add Wellness Health Check

- api/pom.xml
- api/src/main/java/io/smallrye/health/api/AsyncHealthCheck.java
- implementation/src/main/java/io/smallrye/health/HealthMessages.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealth.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/ChangingLivenessHealthCheck.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/ChangingReadinessHealthCheckAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/FailedLivenessAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/FailedReadinessAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessLiveness.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessLivenessAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessReadiness.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessReadinessAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/AllCustomFailedTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/AsyncFailedHealthTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/AsyncHealthTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/AsyncSyncHealthTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/ChangingHealthTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/DeploymentUtils.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/MultipleCustomFailedTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/SingleCustomSuccessfulTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/TCKBase.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/WellnessFailedTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/WellnessSuccessfulTest.java
> issue100 Add support for asynchronous checks

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessfulWellnessAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/WellnessSuccessfulTest.java
> Add async wellness support

- api/src/main/java/io/smallrye/health/api/HealthRegistry.java
- implementation/src/main/java/io/smallrye/health/AsyncHealthCheckFactory.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- implementation/src/main/java/io/smallrye/health/registry/AbstractHealthRegistry.java
- implementation/src/main/java/io/smallrye/health/registry/LivenessHealthRegistry.java
- implementation/src/main/java/io/smallrye/health/registry/ReadinessHealthRegistry.java
- implementation/src/test/java/io/smallrye/health/HealthRegistryTest.java
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
> Add health registry experimental feature

- api/src/main/java/io/smallrye/health/api/AsyncHealthCheck.java
- api/src/main/java/io/smallrye/health/api/HealthRegistry.java
> Fix javadoc issues in the API module

- .github/workflows/build.yml
> Fix quality GitHub action execution

- .github/workflows/build.yml
An additional part of #127 as I believe that the PR author should fix the Javadoc issues directly in the PR. Feel free to discuss this.
> Add javadoc executions also for the pull request github actions

- implementation/src/main/java/io/smallrye/health/HealthStatus.java
- implementation/src/main/java/io/smallrye/health/Response.java
- implementation/src/main/java/io/smallrye/health/ResponseBuilder.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealth.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- implementation/src/test/java/io/smallrye/health/HealthCheckResponseProviderTest.java
- implementation/src/test/java/io/smallrye/health/HealthRegistryTest.java
- implementation/src/test/java/io/smallrye/health/HealthStatusTest.java
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
- provided-checks/src/main/java/io/smallrye/health/checks/AbstractHeapMemoryHealthCheck.java
- provided-checks/src/main/java/io/smallrye/health/checks/InetAddressHealthCheck.java
- provided-checks/src/main/java/io/smallrye/health/checks/SystemLoadHealthCheck.java
- provided-checks/src/main/java/io/smallrye/health/checks/ThreadHealthCheck.java
- provided-checks/src/main/java/io/smallrye/health/checks/UrlHealthCheck.java
- provided-checks/src/test/java/io/smallrye/health/checks/InetAddressHealthCheckTest.java
- provided-checks/src/test/java/io/smallrye/health/checks/SocketHealthCheckTest.java
- provided-checks/src/test/java/io/smallrye/health/checks/UrlHealthCheckTest.java
This is a breaking change to make the HealthCheckResponse possible to work with JSON-B. Draft PR as we don't have final spec release with this change yet.
> Rename state references to status

- .github/workflows/build.yml
- implementation/src/main/java/io/smallrye/health/HealthStatus.java
- testsuite/tck/src/main/java/io/smallrye/health/SmallRyeHealthGroupServlet.java
- testsuite/tck/src/main/java/io/smallrye/health/SmallRyeHealthServlet.java
- testsuite/tck/src/main/java/io/smallrye/health/SmallRyeLivenessServlet.java
- testsuite/tck/src/main/java/io/smallrye/health/SmallRyeReadinessServlet.java
- testsuite/tck/src/main/java/io/smallrye/health/SmallRyeWellnessServlet.java
> Fix sonar quality gate

- ui/src/main/webapp/health-ui/index.html
- ui/src/main/webapp/health-ui/style.css
Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>
> reference style.css to allow override in runtimes

- api/src/main/java/io/smallrye/health/api/Startup.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/FailedStartup.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/FailedStartupAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessfulStartup.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessfulStartupAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/StartupFailedTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/StartupSuccessfulTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/TCKBase.java
- testsuite/tck/src/main/java/io/smallrye/health/SmallRyeStartupServlet.java
> Add startup health check group

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
> [2.2.x] Fix duplicate checks registration in health registries

- api/src/main/java/io/smallrye/health/api/Startness.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/FailedStartness.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/FailedStartnessAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessfulStartness.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessfulStartnessAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/StartnessFailedTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/StartnessSuccessfulTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/TCKBase.java
- testsuite/tck/src/main/java/io/smallrye/health/SmallRyeStartnessServlet.java
> Rename Startup annotation to Startness

- provided-checks/src/main/java/io/smallrye/health/checks/AbstractHeapMemoryHealthCheck.java
- provided-checks/src/main/java/io/smallrye/health/checks/HeapMemoryHealthCheck.java
- provided-checks/src/main/java/io/smallrye/health/checks/NonHeapMemoryHealthCheck.java
> [#195] fix names of memory checks

- pom.xml
> Update MP Health to 3.0

- implementation/src/main/java/io/smallrye/health/ResponseBuilder.java
> keeping insertion order in ResponseBuilder

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/NullHealthCheckProducer.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/NullHealthCheckProducerTest.java
> Ignore null health checks

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- pom.xml
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/FailedStartupAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/SuccessfulStartupAsync.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/SingleStartupAsyncFailedTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/SingleStartupAsyncSuccessfulTest.java
- testsuite/tck/src/main/java/io/smallrye/health/SmallRyeStartupServlet.java
Including rename of Startness to Startup
> Update MP Health to 3.1-RC2

- pom.xml
> Add jacoco plugin configuration

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- implementation/src/main/java/io/smallrye/health/registry/StartupHealthRegistry.java
- implementation/src/main/java/io/smallrye/health/registry/WellnessHealthRegistry.java
- implementation/src/test/java/io/smallrye/health/HealthRegistryTest.java
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
> Add health registries for wellness and startup

- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
- pom.xml
- testsuite/experimental/src/test/java/io/smallrye/health/test/SingleStartupAsyncFailedTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/SingleStartupAsyncSuccessfulTest.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/TCKBase.java
- testsuite/tck/src/main/java/io/smallrye/health/SmallRyeStartupServlet.java
> Rename /health/start to /health/started according to the specification

- .github/workflows/pre-release.yml
> Add Integration verification job to pre-release workflow

- implementation/pom.xml
- implementation/src/test/java/io/smallrye/health/HealthCheckResponseProviderTest.java
- implementation/src/test/java/io/smallrye/health/HealthRegistryTest.java
- implementation/src/test/java/io/smallrye/health/HealthStatusTest.java
- implementation/src/test/java/io/smallrye/health/ResponseBuilderTest.java
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
- provided-checks/pom.xml
- provided-checks/src/test/java/io/smallrye/health/checks/InetAddressHealthCheckTest.java
- provided-checks/src/test/java/io/smallrye/health/checks/SocketHealthCheckTest.java
- provided-checks/src/test/java/io/smallrye/health/checks/UrlHealthCheckTest.java
> Upgrade to JUnit 5

- implementation/pom.xml
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
- pom.xml
> Integrate smallrye-testing

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/DisableHealthCheckTest.java
> Allow to disable checks with configuration

- implementation/src/main/java/io/smallrye/health/AsyncHealthCheckFactory.java
- implementation/src/test/java/io/smallrye/health/ProgrammaticAccessSanityTest.java
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
> Add ProgrammaticAccessSanityTest

- implementation/src/main/java/io/smallrye/health/AsyncHealthCheckFactory.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- implementation/src/test/java/io/smallrye/health/AsyncHealthCheckFactoryTest.java
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
> Allow to override config values programmatically

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
> Make Unis lists thread-safe

- .github/project.yml
> Release 4.0.1

- .github/workflows/pre-release.yml
> Add version to the wfly build in pre-release workflow

- ui/pom.xml
> Upgrade download-maven-plugin to 1.7.0

- implementation/src/main/java/io/smallrye/health/AsyncHealthCheckFactory.java
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
> Add exception class and message to exception data

- .github/workflows/pre-release.yml
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
Fix error handling in pre-release verification
> Fix Uni recreating for context propagation

- api/pom.xml
- api/src/main/java/io/smallrye/health/api/HealthContentFilter.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/TestHealthContentFilter.java
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/TestHealthContentFilter2.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/HealthContentFilterTest.java
Requested in https://github.com/quarkusio/quarkus/issues/39369.
Fixes #556
> Implement health filters feature

- api/src/main/java/io/smallrye/health/api/event/HealthStatusChangeEvent.java
- implementation/src/main/java/io/smallrye/health/HealthLogging.java
- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
- pom.xml
- testsuite/experimental/src/test/java/io/smallrye/health/deployment/TestHealthObserver.java
- testsuite/experimental/src/test/java/io/smallrye/health/test/HealthObserversTest.java
> Implement health observers for base health types

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
> Fix possible RC in the SmallRyeHealthReporter

- implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java
- implementation/src/test/java/io/smallrye/health/SmallRyeHealthReporterTest.java
> Remove health check Uni caching

- api/pom.xml
- implementation/pom.xml
- pom.xml
- provided-checks/pom.xml
- release/pom.xml
- testsuite/experimental/pom.xml
- testsuite/pom.xml
- testsuite/tck/pom.xml
- ui/pom.xml
> Next is 5.0.0
